package com.parevetimer.app;

import android.Manifest;import android.app.Activity;import android.appwidget.AppWidgetManager;import android.content.*;import android.content.pm.PackageManager;import android.os.*;import android.view.View;import android.widget.TextView;import java.util.Locale;

public class MainActivity extends Activity {
 private final Handler handler=new Handler(Looper.getMainLooper()); private TextView countdown,category,percent,beefDuration,dairyDuration; private ProgressRingView ring; private View choice,timerPanel,parevePanel;
 private final Runnable tick=()->{updateUi();handler.postDelayed(thisTick(),500);}; private Runnable thisTick(){return tick;}
 @Override protected void onCreate(Bundle b){super.onCreate(b);if(!Prefs.isOnboarded(this)){startActivity(new Intent(this,OnboardingActivity.class));finish();return;}setContentView(R.layout.activity_main);NotificationHelper.createChannels(this);bind();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},700);findViewById(R.id.beef_card).setOnClickListener(v->{TimerManager.start(this,TimerManager.BEEF);updateUi();});findViewById(R.id.dairy_card).setOnClickListener(v->{TimerManager.start(this,TimerManager.DAIRY);updateUi();});findViewById(R.id.settings_button).setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));findViewById(R.id.cancel_text).setOnClickListener(v->{TimerManager.cancel(this);updateUi();});TimerManager.restore(this);}
 private void bind(){countdown=findViewById(R.id.countdown_text);category=findViewById(R.id.timer_category);percent=findViewById(R.id.progress_percent);beefDuration=findViewById(R.id.beef_duration);dairyDuration=findViewById(R.id.dairy_duration);choice=findViewById(R.id.choice_container);timerPanel=findViewById(R.id.timer_panel);parevePanel=findViewById(R.id.pareve_panel);ring=findViewById(R.id.progress_ring);}
 @Override protected void onResume(){super.onResume();if(countdown!=null){updateUi();handler.post(tick);}} @Override protected void onPause(){handler.removeCallbacks(tick);super.onPause();}
 public void updateUi(){beefDuration.setText(shortDur(Prefs.getBeefMs(this)));dairyDuration.setText(shortDur(Prefs.getDairyMs(this)));if(!TimerManager.isActive(this)){timerPanel.setVisibility(View.GONE);parevePanel.setVisibility(View.VISIBLE);ring.setProgress(0);return;}timerPanel.setVisibility(View.VISIBLE);parevePanel.setVisibility(View.GONE);long s=Prefs.get(this).getLong(Prefs.START,System.currentTimeMillis()),e=Prefs.get(this).getLong(Prefs.END,System.currentTimeMillis()),d=Math.max(1,Prefs.get(this).getLong(Prefs.DURATION,e-s)),r=Math.max(0,e-System.currentTimeMillis());countdown.setText(hms(r));category.setText(TimerManager.BEEF.equals(Prefs.get(this).getString(Prefs.CATEGORY,""))?"בשרי":"חלבי");float p=r/(float)d;ring.setProgress(p);percent.setText(String.format(Locale.ROOT,"%d%% נשארו",Math.round(p*100)));}
 private String hms(long ms){long t=(ms+999)/1000;return String.format(Locale.ROOT,"%02d:%02d:%02d",t/3600,(t%3600)/60,t%60);} private String shortDur(long ms){long t=ms/60000,h=t/60,m=t%60;if(h>0&&m>0)return h+" שעות ו־"+m+" דק׳";if(h>0)return h+(h==1?" שעה":" שעות");return m+" דק׳";}
 public static void refreshWidgets(Context c){AppWidgetManager m=AppWidgetManager.getInstance(c);Intent i=new Intent(c,TimerWidgetProvider.class).setAction(AppWidgetManager.ACTION_APPWIDGET_UPDATE);i.putExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS,m.getAppWidgetIds(new ComponentName(c,TimerWidgetProvider.class)));c.sendBroadcast(i);}
}